use_frameworks!
platform :ios, '8.3'

target 'CollectionPickerView_Example' do
  pod 'CollectionPickerView', :path => '../'

  target 'CollectionPickerView_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.1'
  end
end
