use_frameworks!
platform :ios, '8.3'

target 'CollectionPickerView_Example' do
  pod 'CollectionPickerView', :path => '../'

  target 'CollectionPickerView_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.3.2'
  pod 'Nimble', '~> 7.3.1'
  end
end
