use_frameworks!
platform :ios, '8.3'

target 'CollectionPickerView_Example' do
  pod 'CollectionPickerView', :path => '../'

  target 'CollectionPickerView_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
